# Generated by Django 5.0.2 on 2024-02-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientes',
            name='fecha_regitro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
