# Generated by Django 5.0.2 on 2024-02-20 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_ingredientes_fecha_regitro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientes',
            name='fecha_regitro',
        ),
    ]
