# Generated by Django 5.0.2 on 2024-02-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_ingredientes_fecha_regitro'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientes',
            name='fecha_regitro',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredientes',
            name='hora_registro',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
