# Generated by Django 5.0.2 on 2024-02-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_ingredientes_fecha_regitro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientes',
            name='nombre',
            field=models.CharField(error_messages={'unique': 'el registro ya existe!!'}, max_length=100, unique=True),
        ),
    ]
